name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # or the default branch of your repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build.server

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Change to the directory with the built files
